# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1a8225085cf01da6f5608cfbbba0c699686fbf07845de010faedd9a9cc20aa1718dd6e72696ae20e7d59451ffea1a43e92b8b1c098dd4bd0244c32171907945

test:
  secret_key_base: ecd53de2514fb7052bca66341a99d8c1f1635b65b42ba0bc252e8f56472a3c1bcd9c47c2fdbc018414028db3e748369b809e499d9d67a2472ac89600d3fe6366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
